### ISSUE TITLE
Adding a feature to add symbols, equations, draw figures and will try to add more

### ISSUE THREAD

**Issue by kshitijsoni** [vinalbagaria/virtualVidyalaya#2]

**Comment by kshitijsoni** [comment]
I want to contribute---
 a)  in creating a feature that will help the students to write mathematical equations 
 b) in adding symbols( greek alphabets, constants in physics, maths, etc.)
 c) providing scientific calculator facility (focusing on engineering studentrs)

will try to add more. 

Looking forward to hearing from you.

**Comment by vinalbagaria** [comment]
Thank you if you want to contribute you can fork the project and add on your features to it, but for this project we aren't accepting open source contributions.
